name: Compile Chrome Decrypt

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner with Visual Studio installed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSVC environment
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cl /EHsc chrome_decrypt.cpp oleaut32.lib shell32.lib advapi32.lib shlwapi.lib

      - name: Save output
        run: |
          mkdir -p artifacts
          copy chrome_decrypt.exe artifacts/
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: chrome_decrypt_exe
          path: artifacts/chrome_decrypt.exe
